### ISSUE TITLE
Support des langues régionales

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/validateur-bal#49]
## Contexte

Le format BAL prévoit la possibilité de renseigner des libellés en langue régionale pour tous les champs texte en vigueur, et notamment pour `voie_nom`, `commune_nom`, `commune_deleguee_nom`, `lieudit_complement_nom`.

Ces libellés s'ajoutent au libellé "principal", et sont formalisés par une duplication du-dit champ, avec un suffixe (par exemple `voie_nom_bre` pour une variante en breton d'un nom de voie).

https://github.com/BaseAdresseNationale/ban-bal/issues/1

## Travaux nécessaires

La bibliothèque actuelle ne reconnait pas les colonnes additionnelles décrivant les libellés en langue régionale.
Il faut :
- détecter ces champs
- activer la validation sur ces champs
- exposer ces champs dans les entrées `row` via une structure à définir

**Comment by mmortier** [comment]
se baser sur la liste des codes iso 639 2 pour déterminer si le code de langue régionale est valide : https://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-2
Voir pour les codes de langues minorisées des codes provisoires proposés ? cf https://www.openstreetmap.bzh/fr/2018/01/07/28-yezh-minorelaet-e-republik-frans-da-vezan-lakaet-war-gartenn-osm/

**Comment by jdesboeufs** [comment]
Fermé via #57
