### ISSUE TITLE
langues régionales : l'attribut voie_nom_xxx ne peut être vide

### ISSUE THREAD

**Issue by MaelREBOUX** [BaseAdresseNationale/validateur-bal#66]
L'API de dépôt et le validateur indiquent que l'attribut `voie_nom_bre` ne peut être vide.

Or, en toute logique il me semble évident que l'attribut supplémentaire et optionnel `voie_nom_bre` puisse être une chaîne vide car la "traduction" / remise en bonne dénomination peut ne pas être complète du premier coup sur une commune.

![image](https://user-images.githubusercontent.com/6370443/191457796-63043748-4522-4e6f-b9cf-c112f9746a3c.png)

**Comment by MaelREBOUX** [comment]
Croisé avec https://github.com/BaseAdresseNationale/api-depot/issues/35

**Comment by jdesboeufs** [comment]
L'erreur indique `voie_nom`, il semble y avoir un mélangeage de crayons dans la validation.
On regarde ça au plus vite.
