### ISSUE TITLE
Release compilée en .exe

### ISSUE THREAD

**Issue by eprouteau** [BaseAdresseNationale/validateur-bal#77]
Bonjour,

Utilisateur du validateur au format windows pour la publication automatique des Base Adresses locales, Serait-il possible de bénéficier de la dernière version dans ce format ou de m'orienter vers une procédure de compilation ?

Bonne journée,

**Comment by eprouteau** [comment]
Bonjour,

Personne pour apporter de réponse ?

**Comment by fufeck** [comment]
Après avoir télécharger le repo, vous pouvez généré `bal-win.exe` (l'executable windows) avec commande `yarn build` depuis votre terminal
